### ISSUE TITLE
Icons fehlen in der Palette

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.vis-2-widgets-weather-and-heating#29]
Icons werden im Reiter Palette nicht dargestellt.

![Screenshot (874)](https://github.com/user-attachments/assets/01d44ee6-ea4d-468c-a2f1-2a7084769b91)

VIS-2 Wetterwidgets : 0.3.2 
VIS2: 2.9.64

**Comment by rg-engineering** [comment]
sollte bereits behoben sein...

**Comment by sigi2345** [comment]
> sollte bereits behoben sein...

Keine Widgets da?

Wie soll man Richtig updaten?

**Comment by sigi2345** [comment]
Alles Ok, Icons und Installation geklappt.
