### ISSUE TITLE
Wetter Widgets Farben ändern

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.vis-2-widgets-weather-and-heating#51]
Hallo,

kann man den Ort ausblenden oder/und die Farbe ändern und auch bei den Beschriftungen der Achsen?

![Screenshot (981)](https://github.com/user-attachments/assets/5c9ee1f3-a838-4923-9bf3-ee9f1c9b8a88)

**Comment by rg-engineering** [comment]
Den Ort kann man ausblenden, indem man die OID entfernt.

Farben muss ich einbauen...

**Comment by rg-engineering** [comment]
in der 0.7.4. habe ich die Farbeinstellung für den Ort und die Achsbeschriftung hinzugefügt.

**Comment by sigi2345** [comment]
> in der 0.7.4. habe ich die Farbeinstellung für den Ort und die Achsbeschriftung hinzugefügt.

Sehe ich leider nicht?

![Screenshot (1000)](https://github.com/user-attachments/assets/2faf290c-858f-42e7-b7e6-ec22eec4cfbf)

**Comment by rg-engineering** [comment]
sollte eigentlich so aussehen:
![grafik](https://github.com/user-attachments/assets/bc3da095-d5af-4ff3-b62f-fc987c46992b)

Vielleicht das widget neu in den Editor ziehen?

**Comment by sigi2345** [comment]
Ja, funktioniert jetzt.
![Screenshot (1004)](https://github.com/user-attachments/assets/0bd431f4-ae47-44f9-8a60-c61adc7f7212)
