### ISSUE TITLE
Widgets Anpassung

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.vis-2-widgets-weather-and-heating#55]
Hallo,

kann man das anpassen?

![Screenshot2 (1004)](https://github.com/user-attachments/assets/6293eb2f-e6a4-4abb-aeaf-c0e0fc80b781)

- [x] 1. Farbe änderbar
     ist einstellbar
- [x] 2. Beschriftung auch Links
    ist einstellbar
- [x] 3. Beschriftung mittig
         ist bereits mittig, aber die Tabelle darunter ist breiter, als nötig. Hier hilft, das widget einfach kleiner zu machen.
- [x] 4. Farbe änderbar
        die Farben für Überschrift, Status (offen / geschlossen), Raumname und Zeit sind einstellbar
- [x] 5. Bild ?
        Bild ist jetzt im package enthalten und benötigt die alte vis nicht mehr.
- [x] 6. Beschriftung anpassbar
         hier war der default-Wert für die OID des ausgewählten Raumes falsch. (heatingcontrol.0.vis.ChoosenRoom). Raumname und Übersetzung wird nun angezeigt
- [x] 7. Hintergrundfarbe anpassbar
        habe den FilledInput durch OutlinedInput ersetzt und die nutze die Schriftfarbe  des theme (war bisher immer weiß) 
- [x] 8. Hintergrundfarbe anpassbar
     ist einstellbar

**Comment by rg-engineering** [comment]
zu Punkt 3 in obiger Liste:

![grafik](https://github.com/user-attachments/assets/3f33169b-6895-418b-a6a8-bcf4eb903320)

**Comment by rg-engineering** [comment]
zu Punkt 6 in obiger Liste:

![grafik](https://github.com/user-attachments/assets/0b95ee20-f456-4acc-9703-72cea42c0495)

**Comment by rg-engineering** [comment]
zu Punkt 7 in obiger Liste:

![grafik](https://github.com/user-attachments/assets/415251e2-49de-4046-b280-bec1b3fdb6ab)

![grafik](https://github.com/user-attachments/assets/ef71c9e6-a1c8-46a7-94a7-6619529af102)

**Comment by sigi2345** [comment]
Super, DANKE

**Comment by rg-engineering** [comment]
muss noch die Übersetzungen machen, dann erstelle ich ein neues Release...

**Comment by rg-engineering** [comment]
0.7.6 ist released...
