### ISSUE TITLE
[Bug] Fehlermeldungen in der Konsole

### ISSUE THREAD

**Issue by sigi2345** [rg-engineering/ioBroker.vis-2-widgets-weather-and-heating#60]
Hallo,

aktuell gibt es diese Meldungen in der Konsole:

![Screenshot (1049)](https://github.com/user-attachments/assets/e0f8352e-4ab7-4488-9c3b-b68ed8c55e16)

Plattform: Windows
RAM: 15.9 GB
Node.js: v20.18.0
NPM: 10.8.2
Admin: 7.4.0
Vis2: 2.10.7
JS-Controller: 7.0.3

**Comment by rg-engineering** [comment]
sollte mit v0.8.0 wieder funktionieren...
